### PR TITLE
Social Media Website - Milstone #3: Friendshipsv2

### PR DESCRIPTION
**Pull request by diazgio**
### Social Media Website

in this PR we:
- Add Instance variables in user controller for mutual friendship.
- Add helper methods for my user to show mutual friends.
- Add change to the user show page to render mutual friends I choose to show 3 mutual friends max.
- Add basic OOP.

### CODE REVIEW

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

#### Hey team,  your project is looking really good, however, to accomplish as the actual project, you required to do these changes, listed below:
 
_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, to get more knowledge and have a better project to add to your portfolio.
 
 
## [REQUIRED CHANGES]

 - [ ] When a friendship is confirmed, an additional row with reversed user-friend pair is created. (Tip: you'll have to implement a few "has_many" in your User Model, associating confirmed_friendships, friends, pending_friendships, pending_friends, invited_friendships, friend_requests)
- [ ] Please implement the automated tests!
- [ ] You have some rubocop errors, please fix them.
- [ ] User should only see his own posts and his friends posts. (You can implement it by using the SQL query "where", like Post.where(your code))

(I would comment on that user and friendship model, but they were not changed, so I wasn't able to write line comments on it, but with all that info, you can implement the required changes.)


## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Review by Dandush03 — CHANGES_REQUESTED** [review]
# Status: :red_circle: Request Changes :red_circle: 
### Great work implementing all changes, but you must test your controller and fully test your models (like the comment model) before we can let you move forward with the next milestone 
# Happy Coding :computer: :nerd_face:

**Review by javitocor — CHANGES_REQUESTED** [review]
# STATUS CHANGES REQUIRED 🛑 

Hello team!
Nice job implementing the testing for the models! 👏 
But we still need to implement some changes to get this project approved 💪 
Kindly check my comments below 👇  apply the changes and resubmit your project for a new code review ⏩ 

Good luck 😃 

## Mandatory changes
**Add integration and unit tests! Test the controllers as the previous TSE suggested** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

**Comment by diazgio** [comment]
Hi thanks for the advice, I created all the tests for the methods inside of my methods and create the test for the user's controllers.

**Review by rOluochKe — APPROVED** [review]
Hello Team
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
